# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Configures a Kinesis Stream, Lambda function to process the Stream, and the eventsourcemapping to automatically poll the queue for records

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: src/handlers/index.js
  kinesisProcessorFunction:
    DependsOn: kinesisStream
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 15 # This must be <= the Queue Visibiity timeout
      Description: A function that processes Records from Kinesis
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
        # See Policy templates: https://github.com/aws/serverless-application-model/blob/develop/tests/translator/input/all_policy_templates.yaml
        - KinesisStreamReadPolicy:
            StreamName: !Ref kinesisStream
      Events:
        # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-kinesis.html
        KinesisEvent:
          Type: Kinesis
          Properties:
            Stream: !GetAtt kinesisStream.Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
            Enabled: true
            BisectBatchOnFunctionError: true # Do not enable if order is a requirement. Bisect will not preserve order. Instead use Checkpointing.
  
  kinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 2
